# Generated by Django 5.1 on 2024-08-10 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=50, verbose_name='Model name')),
                ('model_year', models.IntegerField()),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('origin_country', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
    ]
